#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "cleanio"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: cleanio [options]"

  opts.on("-p", "--path PATH", "Path to a .rb file or directory") do |path|
    options[:path] = path
  end

  opts.on("--audit", "Run in audit mode to display comments without modifying files") do
    options[:audit] = true
  end
end.parse!

if options[:path]
  begin
    Cleanio::Remover.clean(options[:path], audit: options[:audit])
    if options[:audit]
      puts "Audit completed successfully."
    else
      puts "Cleaning completed successfully."
    end
  rescue StandardError => e
    puts "Error: #{e.message}"
  end
else
  puts "Please provide a file or directory with -p."
end
