#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "cleanio"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: cleanio [options]"

  opts.on("-f", "--file FIle", "Path to .rb file") do |file|
    options[:file] = file
  end
  opts.on("--audit", "Run in audit mode to display file paths and comment lines without modifying files") do
    options[:audit] = true
  end
end.parse!

if options[:file]
  begin
    Cleanio::Remover.clean(options[:file], audit: options[:audit])
    puts "Audit completed successfully." if options[:audit]
    puts "File cleaned successfully." unless options[:audit]
  rescue StandardError => e
    puts "Error: #{e.message}"
  end
else
  puts "Please provide a file path using the -f flag."
end
